/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { AuthContract } from "./Auth";
import { BoxContract } from "./Box";
import { MigrationsContract } from "./Migrations";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Auth"): AuthContract;
      require(name: "Box"): BoxContract;
      require(name: "Migrations"): MigrationsContract;
    }
  }
}

export { AuthContract, AuthInstance } from "./Auth";
export { BoxContract, BoxInstance } from "./Box";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
